### ISSUE TITLE
Styles does not work

### ISSUE THREAD

**Issue by Magum23** [mdx-editor/mdx-editor-in-next#1]
Even with just cloning the repository, the styles to editor are not applied.

**Comment by petyosi** [comment]
Made an update, can you check?

**Comment by Magum23** [comment]
Hi, it still does not look like the demo that is provided on the page, not even when the plugins are added. (maybe it wasn't the intension ?)
![image](https://github.com/mdx-editor/mdx-editor-in-next/assets/49533200/8dacd7f8-8a08-4580-939b-d78413759005)

**Comment by petyosi** [comment]
Oh, you're probably referring to the lack of toolbar? [It's a plugin you need to add](https://mdxeditor.dev/editor/docs/customizing-toolbar).
