### ISSUE TITLE
trying to enable live editing on browser

### ISSUE THREAD

**Issue by orcunTasdemir** [mdx-editor/mdx-editor-in-next#2]
My estimation was that once it is set up the markdown could be edited from the browser and dynamically save and compile back to markdown like the live demo at:
https://mdxeditor.dev/editor/demo
Is there a way to achieve the same editor experience or do I have to edit from the page.tsx file and manually save and compile everytime?
Thanks

**Comment by petyosi** [comment]
If I understand your question correctly, then this is something that you need to do yourself - this is not a feature of the editor.
