### ISSUE TITLE
How to test?

### ISSUE THREAD

**Issue by drac94** [mdx-editor/mdx-editor-in-next#3]
I am trying to do some integration tests but I cannot figure out how to make RTL to see the component, I've put together a small project following the next setup example here https://stackblitz.com/edit/github-gnppze?file=app%2Fpage.tsx but when I run the tests the editor is not rendered. Any idea what could I be doing wrong? Thanks!

**Comment by petyosi** [comment]
Not sure what's the problem with your setup, it could be due to the dynamic imports. Take a look at the test setup of the component itself: https://github.com/mdx-editor/editor/blob/main/src/test/core.test.tsx.
