### ISSUE TITLE
Placeholder showing below the markdown?

### ISSUE THREAD

**Issue by bosheski** [mdx-editor/mdx-editor-in-next#4]
Hello @petyosi, I am incorporating the Mdx editor in my recent Nextjs 14 app router project and I've noticed that whenever I add a placeholder to the editor it creates two ContentEditable divs and the placeholder falls below the markdown.

![410703418_823352956213242_5116270913504086432_n](https://github.com/mdx-editor/mdx-editor-in-next/assets/30408073/06046315-3e56-47ae-9559-a51b0a11e520)

I've followed the same setup that you have applied in this repo and all I have added additionally is a placeholder.

What could be the issue?

**Comment by petyosi** [comment]
That's how Lexical placeholder works. The second element is not contentEditable, but it has the same class as the content editable one, so that the text in it looks the same.
