### ISSUE TITLE
Headings not working

### ISSUE THREAD

**Issue by lpaarup** [mdx-editor/mdx-editor-in-next#5]
Hi @petyosi ,

I was trying to integrate the editor into my next.js 14 app and the headings were not working. I am adding the headingsPlugin and BlockTypeSelect, but the text will be a normal paragraph regardless of the heading type on the toolbar.

I've tried this example repo and the next-pages one and they don't work either... Do you have an idea of what else I could try?

Thanks

**Comment by petyosi** [comment]
https://github.com/mdx-editor/editor/issues/344 most likely.
